name: Execute Hello script

on:
  workflow_dispatch:

jobs:
  run:
    name: Execute script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        
      - name: Call hello.js
        run: node hello.js
