name: Execute Hello script

on:
  workflow_dispatch:
    inputs:
      json:
        description: 'json'     
        required: true
        default: '{"roles_names": [""],"emails": [ "" ]}'
      username:
        description: 'username'
        required: true
        default: 'Nome do usuário'

jobs:
  run:
    name: Execute script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        
      - name: Call hello.js
        env:
          USERNAME: ${{ github.event.inputs.username }}
          JSON_DATA: ${{ github.event.inputs.json }}
        run: node hello.js
