name: Execute Account script https://github.com/loft-br/auth-roles/blob/a5b15cf81dc694a810ee0a2750d785b000ff3f88/resources/loft.yml

# description: https://github.com/loft-br/auth-roles/blob/a5b15cf81dc694a810ee0a2750d785b000ff3f88/resources/loft.yml

on:
  workflow_dispatch:
    inputs:
      json:
        description: 'json'     
        required: true
        default: '{"roles_names": [""],"emails": [ "" ]}'
      username:
        description: 'username'
        required: true
        default: 'Nome do usuário'

jobs:
  run:
    name: Execute script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        
      - name: Call hello.js
        env:
          CLEINT_ID: ${{ github.secrets.CLIENT_ID }}
          CLEINT_SECRETS: ${{ github.secrets.CLIENT_SECRETS }}
          JSON_DATA: ${{ github.event.inputs.json }}  
        run: 
          echo ${{ github.event.inputs.json }} > users.json 
          node hello.js
